repo: "interactive-svg"
canvasCourse: "467503"
canvasAssignment: "4202401"

naming: true
commits: 2

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - "svg"
      - "svg circle"
      - "svg g"
      - "svg path"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    search:
      - "@keyframes"
      - "transform"
      - "transition"
      - "animation"
